name: C++ Build and Run

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get install g++ -y

      - name: Build program
        run: g++ hello.cpp -o hello

      - name: Run program
        run: ./hello
